import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavBar from "./Navbar";
import { serverSideSupabase } from "./supabaseServerShit/serverSideSupabase";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// @ TODO - need to add the metadatas
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children, modal }: { children: React.ReactNode; modal: React.ReactNode }) {
    const supabase = await serverSideSupabase();

    const {
        data: { user: hasUser },
    } = await supabase.auth.getUser();

    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <div className="flex flex-col h-screen w-full bg-neutral-900 text-white">
                    {/* @TODO - need to fix the user type... */}
                    {hasUser && <NavBar user={hasUser} />}

                    {/* Main content */}
                    <main className="flex-1 w-full overflow-auto p-0.5">{children}</main>

                    {/* Modals or overlays */}
                    <div>{modal}</div>
                </div>
            </body>
        </html>
    );
}
